version: '3.8'
services:
  db:
    container_name: postgres-sql
    image: postgres:15.2-alpine
    restart: always
    networks:
      - hw03-crud
    environment:
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_USER: ashatokhin
      POSTGRES_DB: msaDb
      POSTGRES_PASSWORD: root
      TZ: Europe/Samara
  app:
    container_name: crud-app
    image: avshatokhin/msa:hw03-crud
    networks:
      - hw03-crud
    restart: always
    ports:
      - 80:8000
    environment:
      HTTP_PORT: 8000
      APP_LOG_LEVEL: ERROR
      DB_HOST: jdbc:postgresql://db/msaDb
      DB_USER: ashatokhin
      DB_PASSWORD: root
    depends_on:
      - db

networks:
  hw03-crud: